### ISSUE TITLE
You

### ISSUE THREAD

**Issue by taime** [velopert/react-router-4-demo#1]
There is an error in app.js

In version 4 of react-router you should use import from **react-router-dom** (instead of react-router:
`import { BrowserRouter as Router, Link, Match, Miss } from 'react-router-dom';`

**Comment by velopert** [comment]
I was using pre-release version at that time. This project is now deprecated.

**Comment by chendayang** [comment]
run "npm start",got wrong and couldn't start, after check u code i found u were not using router4,
 i think u should change the name of this repository

**Comment by velopert** [comment]
I've updated the README.md file
